query{
    product(slug: "maquina-de-lavar-brastemp-12kg-branca-com-ciclo-tira-manchas-advanced-e-ciclo-antibolinha"){
        productName
        linkText
        items{
        referenceId{
            Value
        }
        images{
            imageUrl
        }
        sellers{
            addToCartLink
            sellerDefault
            commertialOffer{
            Price
            ListPrice
            Installments{
                Value
                InterestRate
                TotalValuePlusInterestRate
                NumberOfInstallments
                PaymentSystemName
                PaymentSystemGroupName
                Name
            }
            }
        }
        
        }
    }
}